### ISSUE TITLE
是否可以新增miRNA靶基因预测内容

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#103]
Contact: 李丹峰 / 15001878635@163.com
目前网上有一些预测的网站如mirtarbase、miRDB，targetscan等，可否增加多个库同时预测然后去交集较为可信的靶基因预测结果的模块

**Comment by benben-miao** [comment]
上线mirna-prediction: https://hiplot.com.cn/advance/mirna-prediction 程序，实现根据miRNA预测靶gene，根据gene预测靶向miRNA，以及同时预测miRNA和gene的调控关系。程序同时提供3个物种（人类、小鼠、大鼠），14个miRNA在线数据库预测。
