### ISSUE TITLE
在科研文章或者论文中如何进行描述统计分析方法

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#110]
Contact: 天明 / 329340280@qq.com
tmpcode: 72DPpHM
采用你们平台绘制的科研图片后，怎么在英文文章或者中文论文中表述的材料与方法？

**Comment by ShixiangWang** [comment]
根据不同插件提供的参考文献和简洁进行描述，并附近 hiplot 插件 URL 和引用 hiplot 论文？

**Comment by ShixiangWang** [comment]
采用预印本
