### ISSUE TITLE
SHINY UPSETR绘制的upset图导出为空白

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#116]
Contact: 沈倩茜 / sqxkawaii@outlook.com
如题

**Comment by ShixiangWang** [comment]
https://hiplot.com.cn/shiny/upsetr/ 我看了下默认情况是可以正常下载图片

**Comment by dongwei1220** [comment]
可能是导入自己的数据后，选择不了自己数据中指定的集合，导致绘制不出图形，已删除了选定特定集合的功能。
