### ISSUE TITLE
ROC曲线分析待完善

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#129]
Contact: 杨柳风 / 8988711@qq.com
建议增加AUC的95CI。

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/101620212-3a4ec400-3a4f-11eb-94eb-7555f634d34a.png)

有zh置信区间功能，但出来的图挺奇怪的，我有空看下。

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/101791114-1e761b80-3b3e-11eb-896a-525a85047717.png)

源代码没有什么问题，但加置信区间长宽比有点奇怪，调整也不行，被等同放大了。

**Comment by ShixiangWang** [comment]
强制长宽比为1.
