### ISSUE TITLE
id转换

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#130]
Contact: 林运华 / 2935369601@qq.comqq.com
基因id转换用不了什么情况

**Comment by benben-miao** [comment]
1.需要提供具体的问题，如果程序界面无法正常显示需要刷新页面即可显示程序操作界面

2.如果选择其它物种时报错，需要 @Miachol 剑峰检查shiny程序是否library所以的数据库包

3.如果选择对应物种后报错None of the keys entered are valid keys for 'SYMBOL'. Please use the keys method to see a listing of valid arguments.表示该物种没有对应的基因，需要检查基因是否来自于该物种的上游分析。
