### ISSUE TITLE
进行KEGG富集分析时报错

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#146]
Contact: xu jieyun / J_Winny@outlook.com
org.DB选择org.Hs.eg.db，样品为人样品，输入的信息只填了SYMBOL一列，无法运算出结果
Reading KEGG annotation online:fail to download KEGG data... Error in download.KEGG.Path(species) : 'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'... Calls: run_hiplot -> eval -> eval -> <Anonymous> -> download.KEGG.Path Execution halted

**Comment by jjyao111** [comment]
请问问题解决了吗，我也遇到了相同的问题

**Comment by Miachol** [comment]
------------------ Original ------------------
From:  "许 EAR"<J_Winny@outlook.com>;
Date:  Wed, Dec 23, 2020 04:52 PM
To:  "李剑峰"<lee_jianfeng@hiplot.org>;
Subject:  回复: 进行KEGG富集分析时报错 #146
 
啊原来我忘记选KEGG数据库了，打扰了不好意思……


发件人: 李剑峰
发送时间: 2020年12月23日 16:49
收件人: J_Winny
主题: 进行KEGG富集分析时报错 #146


你 KEGG DB 参数填的什么？


Contact: xu jieyun / J_Winny@outlook.com
org.DB选择org.Hs.eg.db，样品为人样品，输入的信息只填了SYMBOL一列，无法运算出结果
Reading KEGG annotation online:fail to download KEGG data... Error in download.KEGG.Path(species) : 'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'... Calls: run_hiplot -> eval -> eval -> -> download.KEGG.Path Execution halted

**Comment by jjyao111** [comment]
library("clusterProfiler")
rt=read.table("id.txt",sep="\t",header=T,check.names=F)
rt=rt[is.na(rt[,"entrezID"])==F,]

geneFC=rt$logFC
gene=rt$entrezID
names(geneFC)=gene

#kegg富集分析
kk <- enrichKEGG(gene = gene, organism = "hsa", pvalueCutoff =0.05, qvalueCutoff =0.05)
write.table(kk,file="KEGG.txt",sep="\t",quote=F,row.names = F)
我的代码是这个，请问为什么显示Reading KEGG annotation online:fail to download KEGG data... Error in download.KEGG.Path(species) : 'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'...

**Comment by Miachol** [comment]
可能和你所在的网络环境访问 KEGG 网站比较慢有关系
