### ISSUE TITLE
可否增加柱状散点图

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#148]
Contact: yilixu / yilixu@csu.edu.cn
非常喜欢这个网站，简直是神器，大赞👍👍
但是找了一圈好像没有柱状散点合并在一起的作图工具？只有单独的柱状图或散点图。但是现在很多杂志都要柱状散点合并在一起的图了，单独的柱状图不要。不知道可否添加这一工具？感谢👍👍

**Comment by ShixiangWang** [comment]
目前的柱状图是直接指定了 bar 高，按理是不支持加散点图的，感觉这个需求更符合箱线图的工作，不过看到 benben 已经写过一个插件 https://hiplot.com.cn/basic/barplot-errorbar，但不支持散点

我接下来直接根据 https://rpkgs.datanovia.com/ggpubr/reference/ggbarplot.html 开放一个 hiplot 的界面接口～

**Comment by ShixiangWang** [comment]
@Miachol 添加了 ggbarplot 的插件版本 https://github.com/hiplot/scripts-basic/tree/master/r/barplot-ggpubr，这样就可以非常灵活了。但目前 ui 特别难搞，需要有时间处理下，特别注意其中有一些 json 数组以及初始值为 null 的选项。

后面我看看能不能找个或整个简单的工具来生成 ui.json，目前选项很多都不知道怎么写，多了特别麻烦。

**Comment by ShixiangWang** [comment]
接下来参考 ggboxplot 提供一个 ggbarplot 接口

**Comment by Miachol** [comment]
https://hiplot.com.cn/basic/barplot-errorbar
