### ISSUE TITLE
线性回归中增加p值

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#154]
Contact: 刚成诚 / gangcc@ms.iswc.ac.cn
你好，请问能够在线性回归图中增加p值？另外回归的公式、R2和p值的显示能否上中下排列，一行显示显的有点拥挤，谢谢！

**Comment by ShixiangWang** [comment]
https://hiplot.com.cn/basic/line-regression 可以考虑增加选项分别控制标签位置以及p值

**Comment by ShixiangWang** [comment]
注释位置不是很好修改以及不确定有没有必要修改，jack 师兄可以看下
