### ISSUE TITLE
PCA分析中没能展示出两个分组

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#164]
Contact: 张磊 / 18697327076@163.com
PCA分析中的示例数据，分了两个分组，但是输出的图片中并没有区分两组，而是将每一个样本都进行了标注，这样的话看不出两组的差异

**Comment by ShixiangWang** [comment]
确实需要优化，另外 tsne 图也是一样的  https://hiplot.com.cn/basic/tsne

@mingjiewang

**Comment by Miachol** [comment]
added color and shape column parameters (v.0.1.1)
