### ISSUE TITLE
列线图跑出来的结果是反的

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#209]
Contact: Feng jiang / dxyjiang@163.com
你好，使用数据，跑出的列线图的结果是反的，请修正

**Comment by ShixiangWang** [comment]
这个问题是不是已经解决了 @Miachol 我记得哪个用户群里讨论过？

**Comment by Miachol** [comment]
现在输出的生存率还是从小到大

**Comment by Miachol** [comment]
应该是和输入的特征有关系，和 rms 示例数据是一样的
