### ISSUE TITLE
热图颜色设置

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#213]
Contact: 张宸昊 / chzhang14@fudan.edu.cn
tmpcode: EZ4ZAHk
您好，我发现热图图例的连续数值变量从小到大现在是从红色到蓝色，这和一般的习惯似乎不太相符，或许您有时间是否能把两种颜色调换一下，非常感谢您的阅读。

**Comment by ShixiangWang** [comment]
检查发现默认设定已经解决了
