### ISSUE TITLE
Edge Browser BUG

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#227]
Contact: Phileas Ji / jpf007@126.com
When I use edge Browser to open this link https://hiplot.com.cn/basic/ggscatterstats
After I clicked Template Data, the browser side rolling bar disappeared..

**Comment by ShixiangWang** [comment]
没有重复，浏览器的问题？

**Comment by Miachol** [comment]
我加到 Q&A 了：

11. 导入示例数据后，窗口滚动条不见了？

将鼠标移出表格即可。
