### ISSUE TITLE
相关性分析热图

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#232]
Contact: 热国芬 / reguofen@kmmu.edu.cn
1、基础模块中相关性分析热图是默认pearson相关性分析吗，如果数据不服从正态分布，是否就不能用这种方法。
2、基础模块中的简单相关分析，比如IL-6这种细胞因子，名称是不是不能带有中间的连字符，如何修改成可以带连字符号的。

**Comment by ShixiangWang** [comment]
第 2 点本身是支持的。

**Comment by ShixiangWang** [comment]
已测试
