### ISSUE TITLE
请求新增功能

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#239]
Contact: 王亚奇 / 1030872906@qq.com
希望可以开发一个多个变量两组间差异比较的箱式图或者小提琴图（如将riskscore分为高低两组后，分析一键出图高低两组样本12种免疫细胞浸润差异的箱式图或森林图），目前在版块里还没找到可以做这个的

**Comment by ShixiangWang** [comment]
我接下来有空提供一个ggboxplot接口实现可以支持该功能
