### ISSUE TITLE
Go circle plot自己导入的数据运行出错

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#285]
Contact: LIANG / llity@outlook.com
tmpcode: amGifp7
你好，
数据作图出现下面的错误，请查看一下。
https://github.com/wencke/wencke.github.io/issues/4
类似这个问题，Error in stats::runif(scount[sc], df$x[sc] + 0.06, (df$x[sc] + df$xmax[sc] - : invalid arguments。
谢谢

**Comment by llity** [comment]
可能是，输出的term个数小于设置的最大个数，可以测试一下

**Comment by fmygz163** [comment]
请问这种情况怎么处理？
