### ISSUE TITLE
玫瑰图中的一个小bug

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#293]
Contact: Uaknow / uaknow.feiyang@gmail.com
tmpcode: HA2EXs8
示例给的是6组数据，但如果只有4组数据的话，饼图之间的夹角会出现问题，也就是第三组数据与第四组数据是连在一起的。

**Comment by zerostwo** [comment]
尝试四组数据后，未发现问题。

**Comment by ShixiangWang** [comment]
@zerostwo 这种情况你这里回复以后直接关闭即可。
