### ISSUE TITLE
生存分析使用问题

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#300]
Contact: 日光倾城 / 562990272@qq.com
tmpcode: Mytxxbs
输入数据后，无法自动生成图，显示错误

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/115114436-f56d0800-9fc1-11eb-9e3f-dbc3fe491ebf.png)

Y 轴标签没设定造成的。
