### ISSUE TITLE
为何提交运行后，只能看到相关参数代码，没办法查看图片呢？

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#314]
---
due: 2021-04-29
---

Contact: 邵琮翔 / scx0625@126.com
tmpcode: QE54MyT
有的时候就可以出现预览图片，有的时候就只能显示出一堆代码，我的操作都是一样的呀，为啥会这样子呢？

**Comment by ShixiangWang** [comment]
已回应。

后续如果确定操作完全一致，可能是服务器的系统问题，建议多试几次。

**Comment by ShixiangWang** [comment]
无后续回应。
