### ISSUE TITLE
列线图bug

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#315]
---
due: 2021-04-30
---

Contact: lee / 462452679@qq.com
tmpcode: null
如果是miRNA或者免疫细胞名称中间带空格 就会报错

**Comment by ShixiangWang** [comment]
你好，

目前该图（或者说Hiplot大部分图）不支持变量名中带空格，请将空格删除或者使用英文点号替换。如果你确实需要间隔，可以考虑通过PS或AI后期修改。

祝好，
王诗翔
Hiplot
