### ISSUE TITLE
使用建议

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#323]
Contact: 王婷 / 1534270156@qq.com
1、韦恩图，可不可以不要只限定五列为最多可输入的项目，当然可以设置最少几列，但希望可以把最多可输入的项目数增加一下
2、韦恩占比图，希望可以调整图片字体大小
3、第一个热图，需要三个表格全部输入才能出图，可不可以输入任一类型的数据都可以画出相应的图表？
不好意思以上是我自己的使用体验，这些建议也不完全可取，谢谢！

**Comment by ShixiangWang** [comment]
已回应。
