### ISSUE TITLE
箱型图绘制问题

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#327]
---
due: 2021-05-12
---

Contact: Qingbo / zhaoqingbo@sjtu.edu.cn
tmpcode: null
箱型图在绘制过程中，好像只提供了9个分类数，超过了就不能输出。能不能增加到15或者20是不是会更好？

**Comment by ShixiangWang** [comment]
已回复

**Comment by ShixiangWang** [comment]
用户已解决
