### ISSUE TITLE
基础模块坐标轴数据间隔调整

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#335]
Contact: 张路捷 / lujiezhang0917@163.com
比如在绘制频率分布直方图时，X轴和Y轴的数据间隔无法修改，导致数据可视化时不是很美观，希望工作人员能够尽快优化，谢谢！

**Comment by ShixiangWang** [comment]
这要支持一个类似全部 ggplot2 图修改的参数。

**Comment by ShixiangWang** [comment]
`scale_x_continuous` 函数有 `n.breaks` 选项

**Comment by ShixiangWang** [comment]
一个设定参考。

```r
ggplot(worldcup, aes(x = Time, y = Passes, color = Position, size = Shots)) + 
  geom_point(alpha = 0.5) + 
  scale_x_continuous(name = "Time played (minutes)", 
                     breaks = 90 * c(2, 4, 6),
                     minor_breaks = 90 * c(1, 3, 5))
```

![image](https://user-images.githubusercontent.com/25057508/119072274-cbbe5b00-ba1d-11eb-85f8-0462e581d31f.png)
