### ISSUE TITLE
增加kaplan-meier plot的请求

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#34]
Contact: QIAN ZHAO / sjtuzqian@163.com
希望能够增加KM plot,用logrank比较不同治疗间的累积缓解率。谢谢！

**Comment by ShixiangWang** [comment]
这个是不是通过增强 https://hiplot.com.cn/basic/survival 实现？

**Comment by mvpsc30** [comment]
这个已经添加fun选项实现 多谢诗翔提醒
