### ISSUE TITLE
关于图像分辨率的问题

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#347]
---
due: 2021-05-29
---

Contact: Ren Peng / 296143100@qq.com
tmpcode: f4htSmt
您好，hiplot是我目前见到的一款非常棒的在线可视化网站，感谢每位工作者的贡献。
这里，我有一个小建议，请问是否可以在制做图形的过程中加入dpi参数，可以使导出的图片更加清晰

**Comment by ShixiangWang** [comment]
默认导出应该是 300 dpi 吧？

**Comment by Miachol** [comment]
默认 300 dpi，但是如果是使用 jpeg 肯定就压缩了

**Comment by ShixiangWang** [comment]
我觉得单独提供 dpi 设定没有必要。 剑峰你直接回复下，或者说下 pdf 转换为任何格式。
