### ISSUE TITLE
相关系数选择col的时候，x轴和y轴都会少一个

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#348]
---
due: 2021-05-30
---

Contact: pengpeng guan / 1135216327@qq.com
tmpcode: TmPDwsN
相关系数选择col的时候，x轴和y轴都会少一个

**Comment by ShixiangWang** [comment]
@mingjiewang

**Comment by Miachol** [comment]
应该是正常的吧，选 row 也是会分别少第一个和最后一个

**Comment by ShixiangWang** [comment]
是去掉了自相关吗？我没看结果。
