### ISSUE TITLE
花瓣图

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#355]
---
due: 2021-06-03
---

Contact: 吴莹莹 / 109069852@qq.com
tmpcode: r2KbfbJ
数据读取有误

**Comment by ShixiangWang** [comment]
@Miachol 临时码插件好像出问题了，没法查询到相应的结果

```
{"msg":"token expired"}
```

**Comment by Miachol** [comment]
我测试好像是正常的。可能需要刷新网站重新登录下，应该是账号的 token 过期了

> @Miachol 临时码插件好像出问题了，没法查询到相应的结果
> 
> ```
> {"msg":"token expired"}
> ```

**Comment by ShixiangWang** [comment]
哦哦，这样子～
