### ISSUE TITLE
小工具箱内很多功能失效，无法加载

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#367]
---
due: 2021-06-11
---

Contact: Wilbert / 1985018003@qq.com
如题

**Comment by ShixiangWang** [comment]
服务器的问题？一些涉及Shiny类似需要启动额外进程的插件都无法打开了。例如 https://hiplot.com.cn/mini-tools/sra-explorer

![image](https://user-images.githubusercontent.com/25057508/120827286-de906e00-c58d-11eb-8129-e7fa6d6a982a.png)

**Comment by Miachol** [comment]
和前几天 Vue 更新的版本可能有关系，修改 CDN 链接使用上一个版本恢复正常
