### ISSUE TITLE
比例韦恩图

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#37]
Contact: Zhen Wang / slw890624@tamu.edu
tmpcode: NanJxQN
比例韦恩图绘制结果有错误，无法显示三个样品之间重叠的比例

**Comment by ShixiangWang** [comment]
这个 bug 有修正吗？

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/160341552-efdf3b8b-5e5f-4ce2-9b42-55bb9d5cfe2a.png)

将最后一行数据修改为10，出来的图挺奇怪的，需要核查下这种分析的正确性 @Miachol 

![image](https://user-images.githubusercontent.com/25057508/160341623-a95b994b-ee88-4b7e-89c7-bd13a2dc7dcd.png)
