### ISSUE TITLE
三列两种分类失败

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#377]
---
due: 2021-06-17
---

Contact: 大宝 / 947898862@qq.com
Tool: 柱状图 | tmpcode: 4Z24i5G

**Comment by ShixiangWang** [comment]
x 轴支持数值型数据。

![image](https://user-images.githubusercontent.com/25057508/122165919-7bff7200-ceab-11eb-8caa-0da86f0a2856.png)

![image](https://user-images.githubusercontent.com/25057508/122165930-815cbc80-ceab-11eb-9987-b7c87b276240.png)
