### ISSUE TITLE
ggscatterstats绘图报错

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#386]
---
due: 2021-06-24
---

Contact: TIAN ZHENFENG / 653391362@qq.com
Tool: https://hiplot.com.cn/basic/ggscatterstats
ERROR [2021-06-17 10:08:49] Error in p + plot_annotation(title = conf$general$title): non-numeric argument to binary operator

**Comment by ShixiangWang** [comment]
去掉 Group 参数后可以重复该问题：

> ERROR [2021-06-25 10:10:16] Error in p + plot_annotation(title = conf$general$title): non-numeric argument to binary operator

**Comment by ShixiangWang** [comment]
报错的原因是绘图函数本身返回的并不是 ggplot2 兼容的对象：

```
> ggscatterstats(
+     data = mtcars_new,
+     x = wt,
+     y = mpg,
+     label.var = car,
+     label.expression = wt < 4 & mpg < 20,
+     # making further customization with `ggplot2` functions
+     ggplot.component = list(ggplot2::geom_rug(sides = "b"))
+ ) -> p
> class(p)
[1] "ggExtraPlot" "gtable"      "gTree"       "grob"        "gDesc"  
> p + ggplot2::labs(title = "ABC")
Error in p + ggplot2::labs(title = "ABC") : 
  non-numeric argument to binary operator
```

**Comment by ShixiangWang** [comment]
测试网址显示已修复

![image](https://user-images.githubusercontent.com/25057508/123361224-417b9080-d5a1-11eb-82aa-ec6e8da541e2.png)
