### ISSUE TITLE
气泡图报错

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#392]
---
due: 2021-07-01
---

Contact: Lliyan / liyan198208@126.com
Tool: https://hiplot.com.cn/basic/bubble | tmpcode: fKcGT6E
您好，在使用气泡图软件时，总是报错提示哪一行有重复，但是计算的p值等信息，也不能调整，请求帮助。如何解决？

**Comment by ShixiangWang** [comment]
应该是输入数据有问题吧，但已经查阅不到临时码了。如果服务器磁盘目前够用的话，针对注册用户的任务临时保存是否可以延长下？
