### ISSUE TITLE
箱式图的下拉菜单无法弹出

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#396]
---
due: 2021-07-03
---

Contact: 孙丹丹 / 1533624027@qq.com
Tool: https://hiplot.com.cn/basic/ggpubr-boxplot
箱式图的下拉菜单无法弹出，无法选择所需选项，同时也无法手动输入内容，即使输入也立刻变为空白内容

**Comment by ShixiangWang** [comment]
这是json设定的问题还是前端显示的问题？@Miachol 我记得之前没有这种情况
