### ISSUE TITLE
Can't get full visual of x-label and y-label

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#398]
---
due: 2021-07-06
---

Contact: Yusheng HONGE / 784364676@qq.com
Tool: https://hiplot.com.cn/basic/cor-heatmap?lang=en | tmpcode: WwsRYpt
Hi, I'm using the correlation heatmap to draw the picture, and when I put in my data by copy-coller in the table, I found that the image output always missed one or two variable in both x or y axis, that makes the whole image can't use and I don't know why.

**Comment by ShixiangWang** [comment]
已回复。
