### ISSUE TITLE
火山图p阈值横线卡的有问题

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#408]
---
due: 2021-07-12
---

Contact: 蒋自牧 / jzm100jzm@163.com
Tool: https://hiplot.com.cn/basic/volcano | tmpcode: fkzpSZK
我设置了p<0.05，但结果横线没有卡对

**Comment by ShixiangWang** [comment]
@Miachol 

我按示例数据，就修改了 p 值的阈值为 `0.00001` (`1e-5`)，怎么结果图变化挺大的~

![image](https://user-images.githubusercontent.com/25057508/126442323-a4dd793b-ae19-4518-ad95-5ee7e076c304.png)

目前 https://github.com/hiplot/scripts-basic/blob/master/r/volcano/plot.R 的数据预处理可能是有问题的。

**Comment by Miachol** [comment]
滑块有最小 step 的限制，目前修改滑块为带选项的输入框
