### ISSUE TITLE
拷贝数示例数据

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#41]
Contact: 李子都 / lizidu@yeah.net
想试试您们的拷贝数 可视化，但是发现你们提供的示例数据链接不能打开

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/93299241-54e61800-f827-11ea-8211-108843f82295.png)

因为没有翻墙所以打开不了 

@Miachol 剑峰你将这个下载到服务器放到公共路径里面，然后修改下链接？

![image](https://user-images.githubusercontent.com/25057508/93299379-852db680-f827-11ea-9687-ef5ae556a9b1.png)
