### ISSUE TITLE
关于时间依赖ROC曲线绘图

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#410]
---
due: 2021-07-16
---

Contact: Luo / a460442253@qq.com
Tool: 时间依赖ROC | tmpcode: fTBrJFA
无法运行这个版块，哪怕使用示例文件也无法，错误代码如下：
ERROR [2021-07-09 18:41:21] Error in if (slev[1] == 0 & slev[2] == 1) return(D): missing value where TRUE/FALSE needed

**Comment by ShixiangWang** [comment]
示例正常
