### ISSUE TITLE
网址为 https://shiny.hiplot.com.cn/3-line-table 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。进阶模块好多都用不了啦

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#420]
---
due: 2021-08-02
---

Contact: sspectre / 13882701231@163.com
Tool:  https://shiny.hiplot.com.cn/3-line-table | tmpcode: CMxBizN
网址为 https://shiny.hiplot.com.cn/3-line-table 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。进阶模块好多都用不了啦

**Comment by ShixiangWang** [comment]
@Miachol Shiny 是在迁移吗？

**Comment by Miachol** [comment]
SSL 证书今天过期了估计，刚更新了下 应该可以了


--------------原始邮件--------------
发件人："Shixiang Wang ***@***.***&gt;;
发送时间：2021年7月26日(星期一) 晚上11:03
收件人："hiplot/gold" ***@***.***&gt;;
抄送："Jianfeng ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [hiplot/gold] 网址为 https://shiny.hiplot.com.cn/3-line-table 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。进阶模块好多都用不了啦 (#420)
-----------------------------------

 

 
@Miachol Shiny 是在迁移吗？
