### ISSUE TITLE
柱状堆积图点击plot后，一直显示与服务器断开，不进行作图

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#423]
---
due: 2021-08-10
---

Contact: jhasgiufoFBU / 654040072@qq.com
Tool: https://hiplot.com.cn/advance/stacked-bar

**Comment by ShixiangWang** [comment]
应该是数据格式不对或者文件上传的问题？ 建议 @ZhiweiBao 检查和补充下示例文件。

**Comment by zwbao** [comment]
示例数据可参见：https://github.com/zwbao/shinyapps/tree/main/stacked_bar%20/www

**Comment by ShixiangWang** [comment]
@zwbao 更新下插件的README文档或者在Shiny中提供下载示例？

**Comment by zwbao** [comment]
> @zwbao 更新下插件的README文档或者在Shiny中提供下载示例？

嗯，我会更新下
