### ISSUE TITLE
打扰一下，我上传数据之后发现问题

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#456]
---
due: 2021-09-25
---

Contact: yanyumeng / 980035625@qq.com
Tool: https://hiplot.com.cn/advance/clusterprofiler-go-kegg | tmpcode: h2XDz82
您好，我发现上传数据之后没有报错，但是图片却无法显示，请问什么问题呢

**Comment by ShixiangWang** [comment]
应该是没有富集或者数据格式不正确。

但目前临时码系统好像不工作，没法通过临时码访问记录文件

**Comment by Miachol** [comment]
无富集结果。
