### ISSUE TITLE
Nomogram (logistic) is not working now

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#495]
---
due: 2021-12-01
---

Contact: Kefeng Li / kli@ucsd.edu
Tool: https://hiplot.com.cn/basic/nomogram-logistic | tmpcode: 3prCZna
Dear developers
Thank you very much for your powerful tool. 
I was using the nomogram (logistic) analysis and found the error message below.
ERROR [2021-11-24 09:43:09] Error: object of type 'closure' is not subsettable
It worked before and now it did not work even for the demo data. 
Thanks again for your help. 
I appreciate
Kefeng

**Comment by ShixiangWang** [comment]
感觉像是 datadist 出了问题，但搜索不到源码在哪里。


![image](https://user-images.githubusercontent.com/25057508/143157832-2f07f038-e057-4d14-963c-5d5866ee08c3.png)

要不要单独写一个r包，把Hiplot基础提供的函数全部封装进去，这样方便统一维护，以及查看源代码、帮助文档之类的。

**Comment by Miachol** [comment]
fixed

**Comment by Miachol** [comment]
https://github.com/hiplot/hiplotlib 等有空的时候我封装一下函数

**Comment by ShixiangWang** [comment]
可以的 我有空可以参与文档和测试等编写
