### ISSUE TITLE
新增 ggcorrplot2 相关性热图

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#50]
Contact: Jianfeng / lee_jianfeng@hiplot.org
https://github.com/caijun/ggcorrplot2

![](https://github.com/caijun/ggcorrplot2/raw/master/figs/README-unnamed-chunk-2-5.png)

![](https://github.com/caijun/ggcorrplot2/raw/master/figs/README-unnamed-chunk-3-2.png)

**Comment by benben-miao** [comment]
https://hiplot.com.cn/basic/cor-heatmap

**Comment by ShixiangWang** [comment]
@benben-miao 这个实现方式还是有些不一样的，不过我觉得这个需求也不是很重要。

**Comment by benben-miao** [comment]
我也觉得如此，当时实现X和Blank标记时即是基于ggcorplot2，如果之后绘图有必要再推出新的图也可以
