### ISSUE TITLE
一直失败

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#513]
---
due: 2021-12-28
---

Contact: 雷兴梦 / leixingmeng@163.com
Tool: 箱式图 | tmpcode: XnMY5K8
不知道为什么数据就是按照模板填的 但是一直失败

**Comment by ShixiangWang** [comment]
https://hiplot.com.cn/api/developer/tempcode/XnMY5K8?access_token=9083d8e0-6223-11ec-b521-0fbac6d0715c 最近一直下不了临时码内容，不知道是系统问题还是我这边网络（VPN）问题。

**Comment by Miachol** [comment]
> [hiplot.com.cn/api/developer/tempcode/XnMY5K8?access_token=9083d8e0-6223-11ec-b521-0fbac6d0715c](https://hiplot.com.cn/api/developer/tempcode/XnMY5K8?access_token=9083d8e0-6223-11ec-b521-0fbac6d0715c) 最近一直下不了临时码内容，不知道是系统问题还是我这边网络（VPN）问题。

之前是遍历整个目录，效率比较低，刚优化了下，应该可以了

**Comment by ShixiangWang** [comment]
```
ERROR [2021-12-21 11:41:52] Error in if (str_detect(toupper(conf$extra$pval), "VALUE")) {: argument is of length zero
```

**Comment by ShixiangWang** [comment]
看起来是`conf$extra$pval` 为`NULL`导致的
