### ISSUE TITLE
An error has occurred.

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#517]
---
due: 2021-12-30
---

Contact: Shuhai Zhang / shuhai0292@126.com
Tool: https://hiplot.com.cn/advance/forestplot
Forest map can not be available

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/160339713-45765e27-bf9b-44e0-b2e9-9fa588b0d292.png)

一打开下方显示错误信息。上传示例文件后没看到有反应，同时缺乏一个运行按钮。

@benben-miao

**Comment by Miachol** [comment]
fixed
