### ISSUE TITLE
三元图无法打开

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#518]
---
due: 2021-12-31
---

Contact: huangzq / huangzq681@gmail.com
Tool: https://hiplot.com.cn/advance/ternary-diagram
提示“An error has occurred!"

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/160338787-2ed6d1b8-72d5-4d9a-8ae6-8fac8d9ebf1b.png)
 程序挂掉了

**Comment by Miachol** [comment]
fixed
