### ISSUE TITLE
GSEA分析后显示成功，但没有矢量图

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#521]
---
due: 2022-01-06
---

Contact: 夏韩韩 / xiaxiahan66@163.com
Tool: undefined | tmpcode: HeeX6Rn

**Comment by ShixiangWang** [comment]
@mvpsc30 的确有这个问题，有空检查下喔

**Comment by mvpsc30** [comment]
okok

**Comment by Miachol** [comment]
是因为没有富集到结果。p 要 < 0.1。
