### ISSUE TITLE
金子塔图的

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#531]
---
due: 2022-01-21
---

Contact: haley / hanyu0920@163.com
Tool: https://hiplot.com.cn/basic/pyramid-chart
1.给出的示例图的男女的字体大小不统一；
2.一个建议：能否添加同一个标题下，比如0-4岁区间，男女数目在同一侧进行显示（也就是说，两个条在同一侧显示，更方便只管对比哪个高哪个低），而非金字塔样的在两侧显示。

**Comment by ShixiangWang** [comment]
第2点那就不叫金字塔图了。
