### ISSUE TITLE
网页打不开

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#547]
---
due: 2022-03-15
---

Contact: 二狗子 / reborn32@163.com
Tool: https://hiplot.com.cn/
自21年年底至今，频繁出现hiplot网页和客户端无法打开的情况。
具体表现为：窗口标签上，出现小鲸鱼标志和“Hiplot”，而非正常应该显示的“Hiplot| 生物医学数据可视化……”；同时，整个网页界面一篇空白。
刷新、更换浏览器、更换电脑、清除浏览器缓存等请操作后，仍不能打开。
偶尔又可以正常打开网页。
能否麻烦您给我一点解决建议？谢谢。

**Comment by ShixiangWang** [comment]
是不是要翻墙体验才比较好，我现在感觉不到什么问题，之前有几次访问页面显示有时候会出不来。

**Comment by Miachol** [comment]
cdn.jsdelivr.net 换成 unpkg.com 了，不知道有没有好一点

**Comment by ShixiangWang** [comment]
@Miachol 我目前手机和电脑访问都还比较快，你要不让大家都测试一下？如果都还可以，就没有问题了。
