### ISSUE TITLE
https://hiplot.com.cn/advance/stacked-bar

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#549]
---
due: 2022-03-30
---

Contact: 贺盼弟 / hepandi@163.com
Tool: https://hiplot.com.cn/advance/stacked-bar | tmpcode: y6Te5Dy
Disconnected from the server.

**Comment by ShixiangWang** [comment]
我这边测试没有问题，这个可能跟 Shiny 的响应有关系。
