### ISSUE TITLE
特殊参数perplexity无法修改

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#566]
---
due: 2022-04-17
---

Contact: 孙振飞 / 1452538307@qq.com
Tool: t sne | tmpcode: CMGMbaT
您好，在进行tsne处理数据的时候，特殊参数perplexity无法修改，虽然可以手动输入数值，但是轴上依旧显示的是1，检查了代码，也确实是按照1运行的

**Comment by ShixiangWang** [comment]
https://github.com/hiplot/scripts-basic/blob/7dbcb37adaf18801ebc34cb6aa13ff8d7b3bcbf3/r/tsne/ui.json#L45 

这个设定有问题？

**Comment by Miachol** [comment]
numeric; Perplexity parameter (should not be bigger than 3
          * perplexity < nrow(X) - 1, see details for interpretation

输入的数据只有 4 行
