### ISSUE TITLE
中国地图2 无法显示 draw_map 功能不可用

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#577]
---
due: 2022-05-01
---

Contact: 李飞 / mhxj47@163.com
Tool: /basic/map-china2
中国地图2 无法显示 draw_map 功能不可用

**Comment by ShixiangWang** [comment]
奇怪，这个函数应该 export 出去了呀

https://github.com/hiplot/hiplotlib/blob/f361016c999f4c1626f3ef39c248de0d5346ec22/NAMESPACE#L19

**Comment by Miachol** [comment]
v0.1.0 报的错，其他的正常

**Comment by ShixiangWang** [comment]
> v0.1.0 报的错，其他的正常

加个公告提示下？

**Comment by Miachol** [comment]
打了个补丁，应该可以了
