### ISSUE TITLE
世界地图因draw_map功能无法使用

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#578]
---
due: 2022-05-01
---

Contact: 李飞 / mhxj47@163.com
Tool: /basic/map-world2 | tmpcode: n62Mt2k
ERROR [2022-04-24 17:00:22] Error in draw_map("map-world/world.rds", "ENG_NAME", "Antarctica"): could not find function "draw_map"

**Comment by ShixiangWang** [comment]
已回复
