### ISSUE TITLE
Volcano module color palette adjust problem

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#588]
---
due: 2022-05-18
---

Contact: York Qiu / qiuyuankang@sina.com
Tool: /basic/volcano | tmpcode: cTiDTZt
Hello,
       I am so sorry, but I have to say.
       When use your volcano module to draw a volcano diagram, I find the color palette is not adjustable.That means even though I can change the color palette, I can't change the foreground color of the result volcano diagram.
       Please check if this problem still exists.
                                                                                                                             Yours,
                                                                                                                              York

**Comment by ShixiangWang** [comment]
这个被写死在代码了：

```r
  ref_palette <- c("#2f5688", "#BBBBBB", "#CC0000")
```
