### ISSUE TITLE
请求帮助-咨询

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#590]
Contact: SQH / 15221378017@163.com
制作火山图时，我需要标注某个感兴趣基因名称，但是因为差异比较小，软件自动标注的基因名称被一堆散点遮住  无法显现  如何解决？

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/167807671-80b54422-a1be-4d57-a3b0-f3718d73756f.png)

已有选项
