### ISSUE TITLE
分析绘图报错

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#612]
---
due: 2022-06-14
---

Contact: lucky YANG / yp2099@126.com
Tool: /advance/clusterprofiler-go-kegg | tmpcode: PDXKXEf

**Comment by ShixiangWang** [comment]
https://hiplot.com.cn/api/developer/tempcode/PDXKXEf?access_token=77f6f160-e7d7-11ec-b4ff-a7df7caab712 下载不了，试了退出然后重新登陆

**Comment by Miachol** [comment]
我直接检索的 log，没有这个 tmpcode
