### ISSUE TITLE
GO/KEGG模块选择不同最大基因集，富集结果不一样

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#614]
---
due: 2022-06-24
---

Contact: 陈舒菡 / 903741239@qq.com
Tool: /advance/clusterprofiler-go-kegg
你好，我在做差异基因（共1401个）富集分析时，最大基因集的数目分别选择了100和500，下载的结果显示Qvalue值小于0.05的GO种类差了600多个，富集到的功能也不一样。请问这个最大基因集具体是什么含义？为什么会导致这个误差？我应该选择多少数目的最大基因集？

**Comment by ShixiangWang** [comment]
已回复
