### ISSUE TITLE
WGCNA示例文件无法下载

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#622]
---
due: 2022-07-14
---

Contact: Todd / ilinyikai@163.com
Tool: /advance/wgcna
报错如下
Error: ENOENT: no such file or directory, stat '/cluster/apps/hiplot/userdata/hiplot/fe8dd930-fd9b-11ec-9deb-e316791d3d91/public/demo/wgcna/LiverFemaleClean.txt'
Error: ENOENT: no such file or directory, stat '/cluster/apps/hiplot/userdata/hiplot/fe8dd930-fd9b-11ec-9deb-e316791d3d91/public/demo/wgcna/TraitsClean.txt'

**Comment by ShixiangWang** [comment]
@Miachol 确定了，有空看下？

**Comment by Miachol** [comment]
fixed
