### ISSUE TITLE
barplot gradient的一个建议

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#638]
Contact: barplot gradient / ahmucss@163.com
能不能添加一个选项是barplot gradient的不按p值排序，按照原始数据顺序排序

**Comment by ShixiangWang** [comment]
这样top items就没法定义了。除非这样设计，加一个可选情况只按用户的输入展示，这种情况忽略 top items。

**Comment by Miachol** [comment]
https://github.com/hiplot/scripts-basic/commit/58119c3cef9b7cd0603fce7a98d762ed0ec9d6cb 已支持
