### ISSUE TITLE
转存中文内容时，pdf格式不能显示中文，英文数字能显示

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#65]
Contact: PAN PAN / 861040989@qq.com
tmpcode: mEDdHbs
做散点图的时候，转存中文内容时，pdf格式不能显示中文，英文数字能显示；转存png一切正常！

**Comment by dongwei1220** [comment]
富集气泡图中转存pdf图片时，中文内容也显示不出，但转存png图片时是正常的！

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/94787446-e4352300-0404-11eb-87f3-436dc9a51f74.png)
 和箱线图符号问题是一样的
