### ISSUE TITLE
Sigflow使用示例文件运行仍报错

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#661]
---
due: 2022-10-04
---

Contact: 刘琦 / lq5467z37@163.com
Tool: /advance/sigflow | tmpcode: jf6f3GB
Sigflow即使是使用示例文件运行，仍然报错。

**Comment by ShixiangWang** [comment]
本地已测试解决 extract 问题

**Comment by lq5467z37** [comment]
感谢您的回复，但是我试了下依旧无法出结果
![image](https://user-images.githubusercontent.com/114502825/192692583-2c33a576-b902-4e2d-a81a-b7db72b2e12d.png)
