### ISSUE TITLE
关于数据的数据格式问题

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#68]
Contact: 张家瑜 / pfkxwz@163.com
tmpcode: SATwGp4
尊敬的hiplot老师们：
  关于数据输入的相关问题，有个小小的问题反馈。在各个模块制图的过程中，都需要输入数据，但每次网页右侧的移动条都很不方便，每次往下拉，整个hiplot网页也会跟着往下动。是否可以在输入数据格式的页面进行固定或者弹出来，不然每次很不方便。谢谢！

**Comment by ShixiangWang** [comment]
我感觉直接用鼠标很正常，如果用滚轮或者双指滑动确实有一点这样的问题。我觉得直接使用表格内部右侧的滑块是比较好的，但可能存在两个问题：
1. 滑块可能有点小，看起来不明显
2. 默认是 20 万行，拖动滑块索引变动非常大，是否默认支持1000行展示，但也可以粘贴非常长的数据？或者说默认100/1000行，当数据拷贝进去后会动态增大行数？
