### ISSUE TITLE
预览图打不开

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#699]
Contact: mingchaoshao / 857564258@qq.com
所有的图  预览图打不开

**Comment by ShixiangWang** [comment]
@Miachol 预览图是出问题了。

**Comment by Miachol** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    https://www.imagehub.cc 改版了，不知道之前的图还能不能回来。再等几天，如果还不行估计要全部重新弄了，之前的图片文件没备份...
    
        
            
        
    
    
        
        

        
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Shixiang Wang ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年12月6日 17:50
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [hiplot/gold] 预览图打不开 (Issue #699)
        
      
    
  
  

@Miachol 预览图是出问题了。

**Comment by ShixiangWang** [comment]
啊，这么尴尬～
