### ISSUE TITLE
箱式图统计的P值位置、γδ T cell字体无法正常显示，还有多组图的排列顺序需按照表格顺序，以上请求帮忙调整

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#70]
Contact: 耿维 / 164241193@qq.com
tmpcode: aAfWXAF

**Comment by ShixiangWang** [comment]
已经找不到数据了。。。

这里多组图也没搞懂是什么意思。

**Comment by Miachol** [comment]
按表格顺序设置因子水平。这个只差字体了。

**Comment by ShixiangWang** [comment]
字体应该是通用问题

**Comment by ShixiangWang** [comment]
测试：

![image](https://user-images.githubusercontent.com/25057508/94786239-48ef7e00-0403-11eb-97f7-4f94c3564363.png)

当作分面列直接就挂掉了

![image](https://user-images.githubusercontent.com/25057508/94786285-57d63080-0403-11eb-94a3-6642d0a5e645.png)

这个问题是目前分面组名不能包含没有意义的 R 符号

![image](https://user-images.githubusercontent.com/25057508/94786445-90760a00-0403-11eb-8a7c-398be646d350.png)

作为分面组别名是可以的

![image](https://user-images.githubusercontent.com/25057508/94786766-fb274580-0403-11eb-9890-df2123a6b52b.png)

作为映射名字也是可以的

![image](https://user-images.githubusercontent.com/25057508/94786924-2dd13e00-0404-11eb-9679-faef28e72341.png)

但查看 pdf 会发现上面两种情况无法生成正确的符号

![image](https://user-images.githubusercontent.com/25057508/94786995-44779500-0404-11eb-9fcb-e2506ab0236b.png)

这是画图设备导致的，我待会做个修改。
