### ISSUE TITLE
今天网页不能使用

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#72]
Contact: HUI LI / 137103678@qq.com
你好，
今天咱们网站打开后，不能往下滚动了，导致只能看到最上面的内容，没办法使用。我使用的是IE浏览器，在打开使用其它网页时不存在该问题。

huili

**Comment by ShixiangWang** [comment]
应该是浏览器的问题了，我今天进过几次 hiplot 都没有任何问题。
