### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#73]
Contact: 张金锋 / zhangjinfeng00@hrbmu.edu.cn
tmpcode: NtsbrPC

**Comment by Miachol** [comment]
Error in fread(parse_file_link(conf$data[["countData"]]$link)) :
  File is encoded in UTF-16, this encoding is not supported by fread(). Please recode the file to UTF-8.
Calls: as.data.frame -> fread
Execution halted

**Comment by ShixiangWang** [comment]
我看到微信群里讨论解决了，先关闭了
