### ISSUE TITLE
帕累托图失败

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#736]
---
due: 2023-10-30
---

Contact: Juno Xiong / xgl150327@163.com
Tool: /basic/pareto-chart | tmpcode: 6StHmSy
只有把x轴和y轴名称都改成跟样本实例一致的才能出图，如果样本数超过8，图片的大小就会有问题。

**Comment by liang09255** [comment]
坐标轴名称问题已提交PR到https://github.com/hiplot/plugins-open/pull/19

图片大小问题没复现出来，应该是通过修改图片宽高能解决的？
