### ISSUE TITLE
scholar api down

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#747]
---
due: 2024-02-02
---

Contact: Shixiang Wang / w_shixiang@163.com
Tool: /advance/tinyscholar
https://api.hiplot.org/google/scholar.php 这个server down了，还能恢复吗？

**Comment by Miachol** [comment]
googlescholar.php 这个文件还有没

**Comment by Miachol** [comment]
fixed

**Comment by ShixiangWang** [comment]
我前两天也看了下，没找到对应的源码了。。。。
