### ISSUE TITLE
基因ID转换工具BUG

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#80]
Contact: 郑鸿 / ziecoe@163.com
载入Ensembl ID的txt文件，能够识别全部基因，默认勾选ENTREZ ID和SYMBOL，下方表格出现转换好的内容，download下载txt，结果里面只有Ensembl ID和ENTREZ ID，没有gene symbol列

**Comment by benben-miao** [comment]
已经修复并提交，可以下载选中的所有需要转换的IDs
