### ISSUE TITLE
弦图提交失败

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#88]
Contact: Jody / 928507074@qq.com
tmpcode: 8KHmhpi
您好：
RPimGwX
8KHmhpi
CRH7cjR
B7yZppp
上述临时码均有问题，或表现为提示错误，或无法输出图像。
经尝试，即便下载示例文件，将首行替换为自己的内容（kegg 通路名称），也无法正常输出图像。
非常期待您的回答，万分感谢！

**Comment by ShixiangWang** [comment]
从群信息看，这个问题是不是已经解决了？
