### ISSUE TITLE
terrible data upload

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#98]
Contact: ivy / 1806192840@qq.com
there is a big difficult in uploading a large amount of data. I had tried so much times but still failed. it's a big problem to import dataframe to Hiplot. wish your fix it and strenghten it as soon as possible.

**Comment by benben-miao** [comment]
Big data files or folders should be upload at "File Manager" menu on hiplot website (https://hiplot.com.cn).

Note:

![File Manager](https://s1.ax1x.com/2020/10/31/BUrRld.jpg)
